// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFK1lW3neK1O1Rki9PcZxvwm8fRf9YyNI',
    appId: '1:561520878152:web:e1893681a6ba5064316e7d',
    messagingSenderId: '561520878152',
    projectId: 'login-fenix',
    authDomain: 'login-fenix.firebaseapp.com',
    storageBucket: 'login-fenix.appspot.com',
    measurementId: 'G-GP0JJJY1FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqNXCCis2ZVnhLmO37XBDhc7Hq_DvgU5s',
    appId: '1:561520878152:android:e7470b4ce9df86af316e7d',
    messagingSenderId: '561520878152',
    projectId: 'login-fenix',
    storageBucket: 'login-fenix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnlZ9HoILREvhKuOamEcfK9p5xEOP0wg',
    appId: '1:561520878152:ios:956e14b54d2431ff316e7d',
    messagingSenderId: '561520878152',
    projectId: 'login-fenix',
    storageBucket: 'login-fenix.appspot.com',
    iosClientId: '561520878152-u4fccm7cc71k69mfs8umoisdeu8pk4e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFenix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnlZ9HoILREvhKuOamEcfK9p5xEOP0wg',
    appId: '1:561520878152:ios:956e14b54d2431ff316e7d',
    messagingSenderId: '561520878152',
    projectId: 'login-fenix',
    storageBucket: 'login-fenix.appspot.com',
    iosClientId: '561520878152-u4fccm7cc71k69mfs8umoisdeu8pk4e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFenix',
  );
}
